# Generated by Django 5.1.5 on 2025-01-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_myfinance_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfinance',
            name='date',
            field=models.DateField(),
        ),
    ]
