# Generated by Django 5.1.5 on 2025-01-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_myfinance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfinance',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='expense', max_length=20),
        ),
    ]
