# Generated by Django 5.1.5 on 2025-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_myfinance_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfinance',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=20),
        ),
    ]
