# Generated by Django 5.1.5 on 2025-01-28 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_myfinance_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfinance',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='finance.mycategory'),
        ),
    ]
