# Generated by Django 5.1.5 on 2025-03-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_myfinance_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfinance',
            name='category',
        ),
    ]
