# Generated by Django 5.1.5 on 2025-03-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_myfinance_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCategory',
        ),
    ]
