import os

from dotenv import load_dotenv

load_dotenv()

CONFIG__SECRET_KEY = os.getenv("CONFIG__SECRET_KEY")
CONFIG__DEBUG = os.getenv("CONFIG__DEBUG")

CONFIG__ALLOWED_HOSTS = os.getenv("CONFIG__ALLOWED_HOSTS")

CONFIG__ACCESS_TOKEN_LIFETIME = int(os.getenv("CONFIG__ACCESS_TOKEN_LIFETIME"))
CONFIG__REFRESH_TOKEN_LIFETIME = int(os.getenv("CONFIG__REFRESH_TOKEN_LIFETIME"))
CONFIG__ROTATE_REFRESH_TOKENS = os.getenv("CONFIG__ROTATE_REFRESH_TOKENS")
CONFIG__BLACKLIST_AFTER_ROTATION = os.getenv("CONFIG__BLACKLIST_AFTER_ROTATION")